### ISSUE TITLE
JS Usage example & Node.js support

### ISSUE THREAD

**Issue by doublex** [bminixhofer/nnsplit#15]
Would it be possible to add a simple "usage" for node.js?

**Comment by bminixhofer** [comment]
Hi, sure. Javascript support is somewhat experimental and [tractjs (the JS backend for NNs) has only recently got support for Node.js](https://github.com/bminixhofer/tractjs/issues/8). I only tested NNSplit in the browser so far and it was less important to me because I didn't need it personally and heard from no one that did.

But I can definitely add a usage example for JS and see where we stand for Node.js support - I'll get back to you.

**Comment by bminixhofer** [comment]
Hi, I'd like to keep this open to track Node.js support and remind me of adding a usage example :)

**Comment by doublex** [comment]
Great news!

**Comment by bminixhofer** [comment]
I just added Node.js support. Starting from 0.4.10 NNSplit is built and tested for Node.js and there's a simple usage example [in the README](https://github.com/bminixhofer/nnsplit#nodejs).
