### ISSUE TITLE
Hi, pip install nnsplit doesn't work

### ISSUE THREAD

**Issue by tartaron** [bminixhofer/nnsplit#73]
Hello, first of all, nnsplit is really cool, it's really great stuff. :)
I'd really like to run nnsplit on my local computer,  but an error occurs when I try to pip install nnsplit:

ERROR: Could not find a version that satisfies the requirement nnsplit (from versions: 0.0.1, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.2.0, 0.2.1, 0.2.2)
ERROR: No matching distribution found for nnsplit

can I get some helps?

**Comment by cjrh** [comment]
Which Python version are you using? If it's 3.10 see #64

**Comment by bminixhofer** [comment]
I'm going to assume this is related to the Python 3.10 issue and close this. If not, please let me know @tartaron.

**Comment by miraclebakelaser** [comment]
@bminixhofer, I get the same issue. I thought it was a Python versioning issue, but it turned out to be an ARM64 architecture compatibility issue with Apple Silicon Macs. The only way to install and use nnsplit is by enabling on Rosetta emulation in the terminal or running Python in x86_64 mode (`arch -x86_64 python -m pip install nnsplit`).
